### spring config ###
spring:
  # set application name
  application:
    name: MoneyChanger
  # set profiles active
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.H2Dialect

management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: 'info, health, prometheus, env'
